import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="nextjs, huntingcoder blog, hunting coder"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* Hero Image */}
        <div className={styles.imagewrap}>
          <img
            className={styles.myImg}
            src="/homeImage.jpg"
            width={237}
            height={158}
            alt="hunting coder"
          />
        </div>

        <h1 className={styles.title}>&lt;HuntingCoder/&gt;</h1>

        <div>
          <h2 className={styles.h2}>Latest Blogs</h2>

          <div className={styles.blogItem}>
            <h3 className={styles.h3}>How to learn JavaScript in 2025?</h3>
            <p className={styles.p}>
              JavaScript is the language used to design logic for the web. Lorem
              ipsum dolor sit amet consectetur adipisicing elit. Hic error
              voluptatum impedit!
            </p>
          </div>

          <div className={styles.blogItem}>
            <h3 className={styles.h3}>Mastering React in 2025</h3>
            <p className={styles.p}>
              React is a JavaScript library for building user interfaces. It
              helps create fast and interactive UIs.
            </p>
          </div>

          <div className={styles.blogItem}>
            <h3 className={styles.h3}>VS Code Tips & Extensions</h3>
            <p className={styles.p}>
              Explore top VS Code extensions that can improve your development
              speed and workflow.
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
